[package]
name = "gauss-quad"
version = "0.1.7"
authors = ["DomiDre <dominiquedresen@gmail.com>", "Johanna Sörngård (jsorngard@gmail.com)"]
keywords = ["gaussian", "quadrature", "numerics", "integration"]
categories = ["Mathematics"]
edition = "2018"
description = "Library for applying Gaussian quadrature to integrate a function"
license = "MIT/Apache-2.0"
repository = "https://github.com/domidre/gauss-quad"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
nalgebra = {version = "0.32", default_features = false, features = ["std"]}
serde = {version = "1.0.192", default_features = false, features = ["alloc", "derive"], optional = true}
rayon = {version = "1.10", optional = true}

[dev-dependencies]
approx = "0.5.1"
criterion = {version = "0.5", features = ["html_reports"]}

[features]
serde = ["dep:serde"]
rayon = ["dep:rayon"]

# docs.rs specific configuration
[package.metadata.docs.rs]
# Document all features
all-features = true
# Defines the configuration attribute `docsrs` which will be passed to rustdoc when running on docs.rs
# This idea was taken from: <https://stackoverflow.com/a/61417700>
rustdoc-args = ["--cfg", "docsrs"]


[[bench]]
name = "legendre"
harness = false

[[bench]]
name = "hermite"
harness = false

[[bench]]
name = "laguerre"
harness = false

[[bench]]
name = "jacobi"
harness = false

[[bench]]
name = "midpoint"
harness = false

[[bench]]
name = "simpson"
harness = false