[package]
name = "gauss-quad"
version = "0.1.7"
authors = ["DomiDre <dominiquedresen@gmail.com>", "Johanna Sörngård (jsorngard@gmail.com)"]
keywords = ["gaussian", "quadrature", "numerics", "integration"]
categories = ["Mathematics"]
edition = "2018"
description = "Library for applying Gaussian quadrature to integrate a function"
license = "MIT/Apache-2.0"
repository = "https://github.com/domidre/gauss-quad"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
nalgebra = "0.30"
serde = {version = "1.0.192", default_features = false, features = ["alloc", "derive"], optional = true}
rayon = "1.8"

[dev-dependencies]
approx = "0.5.1"
criterion = {version = "0.5", features = ["html_reports"]}

[features]
serde = ["dep:serde"]

[package.metadata.docs.rs]
all-features = true

[[bench]]
name = "parallel_memory_layout_benchmark"
harness = false