[package]
name = "gauss-quad"
version = "0.1.7"
authors = ["DomiDre <dominiquedresen@gmail.com>", "Johanna Sörngård (jsorngard@gmail.com)"]
keywords = ["gaussian", "quadrature", "numerics", "integration"]
categories = ["Mathematics"]
edition = "2018"
description = "Library for applying Gaussian quadrature to integrate a function"
license = "MIT OR Apache-2.0"
repository = "https://github.com/domidre/gauss-quad"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
nalgebra = {version = "0.33", default-features = false, features = ["std"]}
serde = {version = "1.0.203", default-features = false, features = ["alloc", "derive"], optional = true}

[dev-dependencies]
approx = "0.5.1"
criterion = {version = "0.5", features = ["html_reports"]}

[features]
serde = ["dep:serde"]

[package.metadata.docs.rs]
all-features = true


[[bench]]
name = "legendre"
harness = false

[[bench]]
name = "hermite"
harness = false

[[bench]]
name = "laguerre"
harness = false

[[bench]]
name = "jacobi"
harness = false

[[bench]]
name = "midpoint"
harness = false

[[bench]]
name = "simpson"
harness = false
